# Generated by Django 4.1.6 on 2023-09-02 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.IntegerField(choices=[(1, '10 AM'), (2, '2 PM'), (3, '6 PM'), (4, '10 PM')])),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booked_seats', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.moviesdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.customer')),
            ],
        ),
    ]
