# Generated by Django 4.1.6 on 2023-09-03 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_date',
            field=models.DateField(default=datetime.date(2001, 1, 1)),
        ),
    ]
